module.exports = {
	"destroyer": "To build a destroyer you need at least 30 fuel, 30 ammunition, 30 steel and 30 bauxite.",
	"rare destroyer": "To build a destroyer you need at least 250 fuel, 30 ammunition, 200 steel and 30 bauxite.",
	"submarine": "To build a destroyer you need at least 250 fuel, 130 ammunition, 200 steel and 30 bauxite.",
	"light cruiser": "To build a light cruiser you need 30 fuel, 30 ammunition, 30 steel and 30 bauxite.",
	"rare light cruiser": "To build a rare light cruiser you need at least 250 fuel, 30 or 130 ammunition, 200 steel and 30 bauxite.",
	"heavy cruiser": "To build a heavy cruiser cruiser you need at least 250 fuel, 30 or 130 ammunition, 200 steel and 30 bauxite.",
	"rare heavy cruiser": "To build a rare heavy cruiser you need at least 270 fuel, 30 ammunition, 330 steel and 130 bauxite.",
	"battleship": "To build a battleship you need at least 400 fuel, 100 ammunition, 600 steel and 30 bauxite.",
	"rare battleship": "To build a rare battleship you need at least 500 fuel, 30 ammunition, 600 steel and 30 bauxite.",
	"seaplane tender": "To build a seaplane tender you need at least 300 fuel, 30 ammunition, 400 steel and 300 bauxite.",
	"light aircraft carrier": "To build a light aircraft carrier you need at least 350 fuel, 30 ammunition, 600 steel and 350 bauxite.",
	"rare light aircraft carrier": "To build a rare light aircraft carrier you need at least 500 fuel, 30 ammunition, 600 steel and 330 bauxite.",
	"aircraft carrier": "To build an aircraft carrier you need at least 400 fuel, 200 ammunition, 500 steel and 700 bauxite.",
	"nagato class": "To build a Nagato class battleship you need at least 1500 fuel, 1500 ammunition, 2000 steel and 1000 bauxite and 1 development material in Large Ship Construction Mode.",
	"taihou class": "To build a Taihou class battleship you need at least 4000 fuel, 2000 ammunition, 5000 steel and 5200 bauxite and 20 development material in Large Ship Construction Mode.",
	"i 401": "To build an I 401 submarine you need at least 3500 fuel, 4500 ammunition, 4500 steel, 2000 bauxite and 1 or 20 development material in Large Ship Construction Mode",
	"yamato class": "To build a Yamato class battleship you need at least 4000 fuel, 6000 ammunition, 6000 steel and 3000 bauxite and 20 development material in Large Ship Construction Mode.",
	"musashi class": "To build a Mushashi class battleship you need at least 1500 fuel, 1500 ammunition, 2000 steel and 1000 bauxite and 20 development material in Large Ship Construction Mode.",
};